import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className= "flex flex-col min-h-screen">
        <header className = "grid grid-cols-5 place-items-center"> 
          <div className="flex flex-row gap-2 p-2 text-white text-xl items-center col-start-5">
            Hunter Hockman 
            <Image
              src="/ProfilePicture.jpg"
              alt="Profile picture of the website owner"
              width={50}
              height={25}
              /> 
          </div>

          <nav className = "flex justify-center col-start-3">
            <ul className="flex flex-row text-5xl text-white gap-36">
              <Link href = "/"> home</Link>
              <Link href = "/about"> about</Link>
              <Link href = "/links"> links</Link>
              <Link href = "/work"> work</Link>
              <Link href = "/contact"> contact</Link> 
            </ul>
          </nav>
        </header>
          
        {children}
      
      </body>
    </html>
  );
}
