import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <header className = "flex flex-row justify-between items-center"> 
          <nav className = "flex grow justify-center">
            <ul className="flex flex-row text-5xl text-white gap-36 mt-14">
              <Link href = "/"> home</Link>
              <Link href = "/about"> about</Link>
              <Link href = "/links"> links</Link>
              <Link href = "/work"> work</Link>
              <Link href = "/contact"> contact</Link> 
            </ul>
          </nav>
          
          {/*
          <div className="flex flex-row gap-2 p-2">
            Hunter Hockman 
            <Image
              src="/ProfilePicture.jpg"
              alt="Profile picture of the website owner"
              width={50}
              height={25}
              /> 
          </div>
          */}
        </header>

        {children}
      </body>
    </html>
  );
}
